// server/routes/testGemini.js
// Temporary route to verify the Gemini API connection.
// Will be removed once real feature routes (roadmap.js, interview.js) exist.
//
// Model + endpoint confirmed directly from the official cURL quickstart
// generated by Google AI Studio for this account's API key (Aug 2026):
// model = gemini-flash-latest, auth via X-goog-api-key header.
// If this breaks in the future, regenerate the quickstart snippet from
// https://aistudio.google.com/app/apikey before changing anything here.

const express = require("express");
const router = express.Router();

const GEMINI_MODEL = "gemini-flash-latest";

router.post("/test-gemini", async (req, res) => {
  try {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: "missing_api_key", message: "GEMINI_API_KEY not set in .env" });
    }

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-goog-api-key": apiKey,
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: "Say hello in one sentence." }],
          },
        ],
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      console.error("Gemini API error:", JSON.stringify(data, null, 2));
      return res.status(502).json({ error: "ai_generation_failed", message: data });
    }

    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
      return res.status(502).json({ error: "empty_response", message: "Gemini returned no text.", raw: data });
    }

    res.json({ message: text });
  } catch (err) {
    console.error("Gemini test error:", err);
    res.status(500).json({ error: "server_error", message: err.message });
  }
});

module.exports = router;